amp:
  brokerURL: "https://amp.iantem.io"
  cacheURL: "https://cdn.ampproject.org"
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxhsXmDPAJ4FA+/zAJunE
    Jwfsm3ZV3QoiayQDmvBKWiBmREMVuD3Ezi4TCRLEKKEcekh+hfz9HKXMkv65yRu+
    1WIxUuzJntkXMhCR9FcOQCGgvoUT9mTUEP1noZ2bjZjO/lqLQzANfwjRhC3vMcQd
    k+Ia05e0ITa8/0I9Wv1ld6crEVPjWVVUaCrG11bt8Nv5z6mKU92WpQdotX8vQqLm
    FY3NOc56gPo7XYcZWJXpMM9I/zNLS3GBTAmot9p33Pt0ENVV3M/a8141iOBi61Hc
    w5uBl0msSyJNGy1DrfTzw9PugsjveOlgDJ0NO8Tal+y825VLieQllWcOgeYuiXCZ
    jkKC1bSYLCG2N2mf4Ejk1W299RkaFr0UPDft+ZXNV2OclrB63RpuzTyEL6cMqTzd
    JcLOcbGalDef+OUfLyYtmp+nTk6vM7cH0e3sp1lB0TdaJ/KAWHyOZ2bUIjOj7brW
    PJiDVXRVgNeOprVnul01NusO1woe7Ncm0iivaabwPER9AWF7n/YthcriXrarKEix
    g0prfrk5Ea+3N25cF6aEMAODynS6IXneKFrY/eRkyIoiy4apcoHegn6KvSoK67P0
    4EWWuaFHrfTsXFSIbUlAGZ3tzzB9gFvEzNpXYgGdovrnb/AOWkJulh6Vk00S5UfS
    Op11O4wL+QjNh5Z+dc3AvE8CAwEAAQ==
    -----END PUBLIC KEY-----
  fronts: ["google.com", "developers.google.com","docs.google.com", "drive.google.com", "console.firebase.google.com", "appengine.google.com", "compute.googleapis.com", "run.googleapis.com", "cloudfunctions.googleapis.com", "container.googleapis.com", "pubsub.googleapis.com", "fonts.googleapis.com", "fonts.gstatic.com", "blogspot.com", "play.google.com",  "developers.google.cn"]
